on:
  push
  # schedule:
  #   - cron: '00 12 * * *'
jobs:
  archive_ipfs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TIMESTAMP=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      - run: |
          git clone --bare https://github.com/ipfs/go-ipfs/ .
          git update-server-info
      - uses: valist-io/valist-github-action@v2
        with:
	  rpc-url: https://rpc.valist.io/mumbai
          private-key: ${{ secrets.PRIVATE_KEY }}
          account: nasdf
          project: git-on-valist
          release: ${{ env.TIMESTAMP }}
          files: '**'
