on:
  push
  # schedule:
  #   - cron: '00 12 * * *'
jobs:
  archive_ipfs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TIMESTAMP=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      - run: |
          git clone --bare https://github.com/ipfs/go-ipfs/ .
          git update-server-info
          mv objects/pack/*.pack .
          git unpack-objects < *.pack
          rm -f *.pack objects/pack/*
      - uses: valist-io/valist-github-action@v2.0.0
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          account: nasdf
          project: git-on-valist
          release: ${{ env.TIMESTAMP }}
          files: '**'